{ lib, config, ... }:

let cfg = config.modules.cloudflared; in
{
  options.modules.cloudflared = {
    tunnelId = lib.mkOption {
      type = lib.types.str;
      description = ''
        Cloudflare Tunnel UUID.
        Create with: cloudflared tunnel login && cloudflared tunnel create ha-tunnel
      '';
    };

    credentialsFile = lib.mkOption {
      type = lib.types.str;
      description = ''
        Path to the tunnel credentials JSON file (store with agenix).
        The file is generated by: cloudflared tunnel create <name>
      '';
    };

    ingress = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      description = "Hostname to backend URL mapping";
      example = { "ha.eepo.boo" = "http://localhost:8123"; };
    };
  };

  config = {
    services.cloudflared = {
      enable = true;
      tunnels.${cfg.tunnelId} = {
        credentialsFile = cfg.credentialsFile;
        ingress = cfg.ingress;
        default = "http_status:404";
      };
    };
  };
}
