name: Flake Check

on:
  push:
  pull_request:

jobs:
  flake-checks:
    name: Check nix flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Check flake
        run: nix flake check --all-systems
