name: Flake Check

on:
  push:
  pull_request:

jobs:
  flake-checks:
    name: Check nix flake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # needed for forgejo runner
      - name: Prepare root container for Nix installer
        run: |
          if ! command -v sudo >/dev/null 2>&1; then
            test "$(id -u)" -eq 0
            ln -s "$(command -v env)" /usr/local/bin/sudo
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          enable_kvm: false
          install_options: --no-daemon

      - name: Check flake
        run: nix flake check --all-systems
